### ISSUE TITLE
Error occurred when use parse function.

### ISSUE THREAD

**Issue by zhaotoday** [sidorares/json-bigint#12]
import JSON from 'json-bigint';

const json = JSON({
  strict: false,
  storeAsString: true
});

const obj = '{"a":"{\"b\":1}"}';  // it works well when: const obj = '{"a":"{\\\\"b\\\\":1}"}';
const.parse(obj);

Why there must be double \？

**Comment by sidorares** [comment]
yrs, your input is not a valid json

instead of ` '{"a":"{\"b\":1}"}'` it should be ` '{"a":{\"b\":1}}'` ( and you don't need to escape `"` inside `'`s, so this is ok, too: 
```js
  const obj = '{"a":{"b":1}}';
  console.log(JSON.parse(obj))
```
