### ISSUE TITLE
Not parse the array enclosed in the object

### ISSUE THREAD

**Issue by semi87** [sidorares/json-bigint#21]
> {"AND": ["8", "8.3"] }

'SyntaxError',
  message: 'Unexpected \'}\'',
  at: 24,
  text: '{"AND": ["!8", "!8.3"] }'

I try parse json but I get a throw like Unexpected '}'.

**Comment by sidorares** [comment]
Can you post full self-contained example @semi87 ?

**Comment by semi87** [comment]
yes of course 
`{
	"1": {
		"parameters": {
			"is_critical": false,
			"sleep_seconds": 10
		}
	},
	"2": {
		"parameters": {
			"is_critical": false,
			"sleep_seconds": 30
		}
	},

	"3": {
		"parameters": {
			"is_critical": false,
			"when": {
				"AND": ["!8", "!8.3"]
			}
		}
	}
}`

**Comment by semi87** [comment]
@sidorares  I'm sorry. I find my mistake. Thank you for your answer.
