### ISSUE TITLE
missing hasOwnProperty function after Parse

### ISSUE THREAD

**Issue by runerback** [sidorares/json-bigint#38]
I got big number serializing problem in JSON, so I decide to override `JSON.parse` and `JSON.stringify` with this package globally, then I encountered some errors in other js codes,

it seems `Object` parsed by `JSONbig` lost `hasOwnProperty` function:

```js
import * as JSONbig from "json-bigint";

var json = '{ "value" : 9223372036854775807, "v2": 123 }';

console.log(
    JSON.parse(json).hasOwnProperty("value")
);

console.log(
    JSONbig.parse(json).hasOwnProperty("value")
);
```

module def for typescript:
```ts
declare module "json-bigint" {
    function parse(text: string, reviver?: (this: any, key: string, value: any) => any): any;
    function stringify(value: any, replacer?: (this: any, key: string, value: any) => any, space?: string | number): string;
    function stringify(value: any, replacer?: (number | string)[] | null, space?: string | number): string;
}
```

got output:

```text
true
console.log(JSONbig.parse(json).hasOwnProperty("value"));
                                ^

TypeError: JSONbig.parse(...).hasOwnProperty is not a function
    at Object.<anonymous> (\resources\json-bigint\dist\index.js:27:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

**Comment by sidorares** [comment]
top level export returns a function, we just [set](https://github.com/sidorares/json-bigint/blob/390482a8b6b460f98c61c3b65915dbd91fc8e7b2/index.js#L11) `.parse` and `.stringify` methods on it to make it easier to work with default option.

Change `console.log(JSONbig.parse(json).hasOwnProperty("value"));` to something like `console.log(JSONbig({}).parse(json).hasOwnProperty("value"));` ( or better, save it earlier as something like `const JSON = JSONBig({/* see options in readme*/});` )

**Comment by runerback** [comment]
it works, thanks.

**Comment by goxr3plus** [comment]
This doesn't work for me 

``` JAVA 
var JSONbig = require('json-bigint');
var JSONBigInt = JSONbig({/* see options in readme*/});
var json = '{ "value" : 9223372036854775807, "v2": 123 }';
console.log(
    JSON.parse(json).hasOwnProperty("value")
);
console.log(JSONBigInt.parse(json).hasOwnProperty("value")); 
```

I ended up using this :

```JAVA
const jsonWithString = JSONbigString.parse(json)
const toString = JSONbigint.stringify(jsonWithString)
console.log(JSON.parse(toString).hasOwnProperty('value'))
```

**Comment by sidorares** [comment]
@goxr3plus this is recent change, to add better protection from prototype pollution I changed the way objects are created from `{}` to `Object.create(null)`, unfortunately this has a side effect you posted. Not sure if there is a better way to make it to turn `'{"__proto___": { "test": true }}' string into `{__proto___: {test: true }}` object rather than `{}` with `{test: true}` prototype

**Comment by goxr3plus** [comment]
@sidorares 

so how should I write my above example in order to work properly?

**Comment by sidorares** [comment]
Objects can be created with null prototype, in that case they won't have `. hasOwnProperty` method.

Safer way to call: 

```js
const example = Object.create(null)
Object.hasOwnProperty.call(example, 'value')
// > false
example.value = 111
Object.hasOwnProperty.call(example, 'value')
// > true

const hasOwnProperty = (object, propertyName) => Object.hasOwnProperty.call(object, propertyName)
hasOwnProperty(example, 'value2')
// > false
hasOwnProperty(example, 'value')
// > true
```

**Comment by goxr3plus** [comment]
Thank you :)

**Comment by klesun** [comment]
But that, like, totally breaks compatibility with `JSON.parse`. Changing whole codebase from `parsed.hasOwnProperty('value')` to `Object.hasOwnProperty(obj, 'value')` just to use this lib is a really big setback.

Is there no option to specify that the proto class should be `Object`, not `null`?

P.S. I did not look to deep, but can't you simply mimick `JSON.parse()`'s behaviour for `__proto__` using [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)? Or just restrict writing to `__proto__` without basing objects on `null`?

**Comment by klesun** [comment]
If this PR does not get accepted anytime soon, can just follow the solution from https://github.com/sidorares/json-bigint/issues/39#issuecomment-692533573 and downgrade to `v0.4.0`:
```
npm install --save json-bigint@0.4.0
```

**Comment by MasterOdin** [comment]
Adding onto this issue, this library is billed as:
> JSON.parse/stringify with bigints support.

and we ended up getting tripped up on this difference of behavior between `JSON.parse` and `JSONbig.parse` and should be prominently documented as such.
