### ISSUE TITLE
Publish an Official Version?

### ISSUE THREAD

**Issue by jmschae** [sidorares/json-bigint#70]
It seems like the head of the master branch has some significant fixes on top of the v1.0.0 version published in 2020. Namely it fixes the high precision decimal number error where a number like -55.03756915452509 ends up parsed into a BigNumber when it doesn't need to be/shouldn't be.

Is there any plan to publish an official version in the near future to provide a better way to access those improvements besides forking the repo and publishing an alternative version of the lib?

**Comment by sidorares** [comment]
yes there is a (short term) plan for me to publish next major version, also a long term plan to get support from one of the js foundations and bring in more maintainers and/or move to the dedicated org come from my personal account

There is a weight of 4.5m monthly downloads ( currently ) that makes me much more conservative here compared to any other my library, in case of any doubt I'd rather not add a feature at this stage rather have a (maintenance/security) risk to all current users.
